USE [master]
GO

/****** Object:  Database [ebanking]    Script Date: 17/05/2016 11:52:04 ******/
DROP DATABASE [ebanking]
GO

/****** Object:  Database [ebanking]    Script Date: 17/05/2016 11:52:04 ******/
CREATE DATABASE [ebanking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ebanking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MYBITDB\MSSQL\DATA\ebanking.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ebanking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MYBITDB\MSSQL\DATA\ebanking_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ebanking] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ebanking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ebanking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ebanking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ebanking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ebanking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ebanking] SET ARITHABORT OFF 
GO

ALTER DATABASE [ebanking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ebanking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ebanking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ebanking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ebanking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ebanking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ebanking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ebanking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ebanking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ebanking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ebanking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ebanking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ebanking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ebanking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ebanking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ebanking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ebanking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ebanking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ebanking] SET  MULTI_USER 
GO

ALTER DATABASE [ebanking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ebanking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ebanking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ebanking] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ebanking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ebanking] SET  READ_WRITE 
GO

